CROSS = "⤫"
TICK = "✓"
DYNAMIC_LOGFILE = "DYNAMIC_ANALYSIS/Logs/dynamic_logs.log"
ERROR_LOGFILE = "DYNAMIC_ANALYSIS/Logs/error_log.log"
ALERT_PAYLOAD_FILE = "DYNAMIC_ANALYSIS/payloads/scanext_payloads.txt"
SERVER_PAYLAOD_FILE = "DYNAMIC_ANALYSIS/payloads/scanext_server_payloads.txt"
